version: '3.7'
services:
  app:
    container_name: subscription
    build:
      context: .
      dockerfile: Dockerfile
      # args:
    image: subscription
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      # - '${APP_PORT:-80}:80'
      - '80:80'
    env_file:
      - .env
    restart: always
    networks:
      - dotnet-network
networks:
  dotnet-network:
    name: dotnet-network
    # external: true
